apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - generated/victoriametrics/templates/vmagent/dep-ds.yaml
  - generated/victoriametrics/templates/vmagent/networkpolicy.yaml
  - generated/victoriametrics/templates/vmagent/pdb.yaml
  - generated/victoriametrics/templates/vmagent/rbac.yaml
  - generated/victoriametrics/templates/vmagent/service.yaml
  - generated/victoriametrics/templates/vmagent/service-account.yaml
  - generated/victoriametrics/templates/vmalert/deployment.yaml
  - generated/victoriametrics/templates/vmalert/networkpolicy.yaml
  - generated/victoriametrics/templates/vmalert/pdb.yaml
  - generated/victoriametrics/templates/vmalert/service.yaml
  - generated/victoriametrics/templates/vmalert/service-account.yaml
  - generated/victoriametrics/templates/vminsert/deployment.yaml
  - generated/victoriametrics/templates/vminsert/networkpolicy.yaml
  - generated/victoriametrics/templates/vminsert/pdb.yaml
  - generated/victoriametrics/templates/vminsert/service.yaml
  - generated/victoriametrics/templates/vminsert/service-account.yaml
  - generated/victoriametrics/templates/vmselect/dep-sts.yaml
  - generated/victoriametrics/templates/vmselect/networkpolicy.yaml
  - generated/victoriametrics/templates/vmselect/pdb.yaml
  - generated/victoriametrics/templates/vmselect/service.yaml
  - generated/victoriametrics/templates/vmselect/service-account.yaml
  - generated/victoriametrics/templates/vmstorage/headless-service.yaml
  - generated/victoriametrics/templates/vmstorage/networkpolicy.yaml
  - generated/victoriametrics/templates/vmstorage/pdb.yaml
  - generated/victoriametrics/templates/vmstorage/service.yaml
  - generated/victoriametrics/templates/vmstorage/service-account.yaml
  - generated/victoriametrics/templates/vmstorage/statefulset.yaml