---
# Source: victoria-metrics-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels: 
    app.kubernetes.io/component: vminsert
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
  name: metering-victoria-metrics-cluster-vminsert
  namespace: default
spec:
  type: ClusterIP
  ports: 
    - name: http
      port: 8480
      protocol: TCP
      targetPort: http
  selector: 
    app: vminsert
    app.kubernetes.io/instance: metering
    app.kubernetes.io/name: victoria-metrics-cluster
---
# Source: victoria-metrics-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels: 
    app.kubernetes.io/component: vmselect
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
  name: metering-victoria-metrics-cluster-vmselect
  namespace: default
spec:
  type: ClusterIP
  ports: 
    - name: http
      port: 8481
      protocol: TCP
      targetPort: http
  selector: 
    app: vmselect
    app.kubernetes.io/instance: metering
    app.kubernetes.io/name: victoria-metrics-cluster
---
# Source: victoria-metrics-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels: 
    app.kubernetes.io/component: vmstorage
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
  name: metering-victoria-metrics-cluster-vmstorage
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports: 
    - port: 8482
      targetPort: http
      protocol: TCP
      name: http
    - port: 8401
      targetPort: vmselect
      protocol: TCP
      name: vmselect
    - port: 8400
      targetPort: vminsert
      protocol: TCP
      name: vminsert
  selector: 
    app: vmstorage
    app.kubernetes.io/instance: metering
    app.kubernetes.io/name: victoria-metrics-cluster
