---
# Source: victoria-metrics-cluster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: 
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: victoria-metrics-cluster-0.41.2
  name: metering-victoria-metrics-cluster
  namespace: default
