---
# Source: victoria-metrics-cluster/templates/vminsert-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/component: vminsert
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
  name: metering-victoria-metrics-cluster-vminsert
  namespace: default
spec:
  selector:
    matchLabels: 
      app: vminsert
      app.kubernetes.io/instance: metering
      app.kubernetes.io/name: victoria-metrics-cluster
  replicas: 2
  template:
    metadata:
      labels: 
        app: vminsert
        app.kubernetes.io/component: vminsert
        app.kubernetes.io/instance: metering
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-cluster
    spec:
      containers:
        - name: vminsert
          image: victoriametrics/vminsert:v1.142.0-cluster
          imagePullPolicy: IfNotPresent
          args: 
            - --envflag.enable
            - --envflag.prefix=VM_
            - --httpListenAddr=:8480
            - --loggerFormat=json
            - --storageNode=metering-victoria-metrics-cluster-vmstorage-0.metering-victoria-metrics-cluster-vmstorage.default.svc.cluster.local.:8400
            - --storageNode=metering-victoria-metrics-cluster-vmstorage-1.metering-victoria-metrics-cluster-vmstorage.default.svc.cluster.local.:8400
            - --storageNode=metering-victoria-metrics-cluster-vmstorage-2.metering-victoria-metrics-cluster-vmstorage.default.svc.cluster.local.:8400
          ports:
            - name: http
              containerPort: 8480
          readinessProbe: 
            failureThreshold: 10
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            tcpSocket:
              port: http
            timeoutSeconds: 5
          resources: 
            requests:
              cpu: 500m
              limits:
                memory: 2Gi
              memory: 512Mi
      serviceAccountName: metering-victoria-metrics-cluster
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 30
