---
# Source: victoria-metrics-cluster/templates/vmselect-server.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metering-victoria-metrics-cluster-vmselect
  namespace: default
  labels: 
    app.kubernetes.io/component: vmselect
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Source: victoria-metrics-cluster/templates/vmselect-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metering-victoria-metrics-cluster-vmselect
  namespace: default
  labels: 
    app.kubernetes.io/component: vmselect
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
spec:
  strategy: {}
  replicas: 2
  selector:
    matchLabels: 
      app: vmselect
      app.kubernetes.io/instance: metering
      app.kubernetes.io/name: victoria-metrics-cluster
  template:
    metadata:
      labels: 
        app: vmselect
        app.kubernetes.io/component: vmselect
        app.kubernetes.io/instance: metering
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-cluster
    spec:
      serviceAccountName: metering-victoria-metrics-cluster
      automountServiceAccountToken: true
      securityContext: 
        {}
      containers:
        - name: vmselect
          securityContext: 
            {}
          image: victoriametrics/vmselect:v1.142.0-cluster
          imagePullPolicy: IfNotPresent
          args: 
            - --cacheDataPath=/cache
            - --envflag.enable
            - --envflag.prefix=VM_
            - --httpListenAddr=:8481
            - --loggerFormat=json
            - --search.maxConcurrentRequests=16
            - --search.maxQueryDuration=5m
            - --storageNode=metering-victoria-metrics-cluster-vmstorage-0.metering-victoria-metrics-cluster-vmstorage.default.svc.cluster.local.:8401
            - --storageNode=metering-victoria-metrics-cluster-vmstorage-1.metering-victoria-metrics-cluster-vmstorage.default.svc.cluster.local.:8401
            - --storageNode=metering-victoria-metrics-cluster-vmstorage-2.metering-victoria-metrics-cluster-vmstorage.default.svc.cluster.local.:8401
          ports:
            - name: http
              containerPort: 8481
          readinessProbe: 
            failureThreshold: 10
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            tcpSocket:
              port: http
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            
      terminationGracePeriodSeconds: 60
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: metering-victoria-metrics-cluster-vmselect
