---
# Source: victoria-metrics-cluster/templates/vmstorage-server.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: 
    app.kubernetes.io/component: vmstorage
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/version: v1.142.0-cluster
    helm.sh/chart: victoria-metrics-cluster-0.41.2
  name: metering-victoria-metrics-cluster-vmstorage
  namespace: default
spec:
  serviceName: metering-victoria-metrics-cluster-vmstorage
  selector:
    matchLabels: 
      app: vmstorage
      app.kubernetes.io/instance: metering
      app.kubernetes.io/name: victoria-metrics-cluster
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels: 
        app: vmstorage
        app.kubernetes.io/component: vmstorage
        app.kubernetes.io/instance: metering
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-cluster
    spec:
      containers:
        - name: vmstorage
          image: victoriametrics/vmstorage:v1.142.0-cluster
          imagePullPolicy: IfNotPresent
          args: 
            - --dedup.minScrapeInterval=30s
            - --envflag.enable
            - --envflag.prefix=VM_
            - --httpListenAddr=:8482
            - --loggerFormat=json
            - --retentionPeriod=1
            - --storageDataPath=/storage
          ports:
            - name: http
              containerPort: 8482
            - name: vminsert
              containerPort: 8400
            - name: vmselect
              containerPort: 8401
          readinessProbe: 
            failureThreshold: 10
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources: 
            requests:
              cpu: 500m
              limits:
                memory: 4Gi
              memory: 1Gi
          volumeMounts:
            - name: 
              mountPath: /storage
            
      serviceAccountName: metering-victoria-metrics-cluster
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 60
  minReadySeconds: 5
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: 
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
