global:
  imageRegistry: ""
  imagePullSecrets: []

clusterDomain: cluster.local

envflagEnable: true
envflagPrefix: VM_
loggerFormat: json

## @section VictoriaMetrics Select Parameters
vmselect:
  image:
    registry: docker.io
    repository: bitnamilegacy/victoriametrics-vmselect
    tag: 1.124.0-debian-12-r0
    pullPolicy: IfNotPresent

  replicaCount: 2

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 1Gi

  kind: deployment

  extraArgs:
    - "-search.maxQueryDuration=5m"
    - "-search.maxConcurrentRequests=16"
    - "-dedup.minScrapeInterval=30s"

  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  affinity: {}
  nodeSelector: {}
  tolerations: []

  ingress:
    enabled: false
    pathType: ImplementationSpecific
    hostname: vmselect.local
    ingressClassName: ""
    path: /
    annotations: {}
    tls: false
    extraPaths: []

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []

  metrics:
    enabled: true

## @section VictoriaMetrics Insert Parameters
##
vminsert:
  image:
    registry: docker.io
    repository: bitnamilegacy/victoriametrics-vminsert
    tag: 1.124.0-debian-12-r0
    pullPolicy: IfNotPresent
    pullSecrets: []

  replicaCount: 2

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 1Gi

  extraArgs:
    - "-replicationFactor=3"
    - "-maxLabelsPerTimeseries=40"

  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  affinity: {}
  tolerations: []

  metrics:
    enabled: true

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}

vmstorage:
  image:
    registry: docker.io
    repository: bitnamilegacy/victoriametrics-vmstorage
    tag: 1.124.0-debian-12-r0
    pullPolicy: IfNotPresent
    pullSecrets: []

  replicaCount: 3

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 4Gi

  retentionPeriod: 3

  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

  affinity: {}
  nodeSelector: {}
  tolerations: []

  metrics:
    enabled: true

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []

  persistence:
    enabled: true
    mountPath: /data
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    dataSource: {}

vmauth:
  enabled: false

## @section VictoriaMetrics Alert Parameters
vmalert:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/victoriametrics-vmalert
    tag: 1.124.0-debian-12-r0
    pullPolicy: IfNotPresent
    pullSecrets: []

  replicaCount: 2

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi

  datasourceUrl: "http://metering-vmselect:8481/select/0/prometheus"

  notifierUrl: ""

  extraArgs:
    - "-evaluationInterval=30s"
    - "-external.label=cluster=central"

  existingRulesConfigMap: "vmalert-config"

  metrics:
    enabled: true

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []

## @section VictoriaMetrics Agent Parameters
vmagent:
  enabled: true

  image:
    registry: docker.io
    repository: bitnamilegacy/victoriametrics-vmagent
    tag: 1.124.0-debian-12-r0
    pullPolicy: IfNotPresent
    pullSecrets: []

  replicaCount: 3

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 2Gi

  kind: deployment

  extraArgs:
    - "-promscrape.cluster.membersCount=3"
    - "-promscrape.cluster.memberLabel=instance"
    - "-promscrape.cluster.replicationFactor=2"
    - "-remoteWrite.maxDiskUsagePerURL=500MB"
    - "-remoteWrite.queues=8"
    - "-remoteWrite.label=monitor=vm-central"

  existingScrapeConfigMap: "vmagent-scrape-config"

  affinity: {}
  nodeSelector: {}
  tolerations: []

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}

  metrics:
    enabled: true