---
# Source: victoriametrics/templates/vmstorage/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: metering-vmstorage
  namespace: "metering"
  labels:
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/version: 1.124.0
    helm.sh/chart: victoriametrics-0.1.31
    app.kubernetes.io/part-of: victoriametrics
    app.kubernetes.io/component: vmstorage
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 80
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: null
      targetPort: http
  selector:
    app.kubernetes.io/instance: metering
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: vmstorage
