---
# Source: victoria-metrics-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metering-victoria-metrics-agent
  namespace: metering
  labels: 
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-agent
    app.kubernetes.io/version: v1.107.0
    helm.sh/chart: victoria-metrics-agent-0.38.0
