---
# Source: victoriametrics/templates/vminsert/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metering-victoriametrics-vminsert
  namespace: "metering"
  labels:
    app.kubernetes.io/instance: metering
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/version: 1.124.0
    helm.sh/chart: victoriametrics-0.1.31
    app.kubernetes.io/part-of: victoriametrics
    app.kubernetes.io/component: vminsert
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: metering
      app.kubernetes.io/name: victoriametrics
      app.kubernetes.io/component: vminsert
